name: "$(BuildDefinitionName) - $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)"

# Exclude all triggers by default
trigger:
  branches:
    exclude:
      - '*'  # Exclude all branches
  paths:
    exclude:
      - '*'  # Exclude all paths

parameters:
  - name: ecp_environment_name
    type: string
    # default must be '<ecp_environment_name>' <-- will be replaced by pipeline deployment
    default: '<ecp_environment_name>'

variables:
- group: "ecp_bootstrap_${{ parameters.ecp_environment_name }}"

pool:
  name: $[variables.ecp_ado_agent_pool_azure]
  demands:
  - ImageOverride -equals ubuntu-24.04

stages:
  - stage: default
    displayName: 'Default'
    jobs:
    - job: adoPoolAnalysis
      displayName: 'ADO Pool Analysis'
      steps:
      - task: Bash@3
        name: adoPoolPipelineInfo
        displayName: 'Azure DevOps Pipeline Info'
        inputs:
          targetType: inline
          script: |
            echo "======================================"
            echo "       Azure DevOps Pipeline Info"
            echo "======================================"
            echo ""
            echo "Organization Information:"
            echo "  Organization URL: $(System.TeamFoundationCollectionUri)"
            echo "  Organization ID: $(System.CollectionId)"
            echo ""
            echo "Project Information:"
            echo "  Project Name: $(System.TeamProject)"
            echo "  Project ID: $(System.TeamProjectId)"
            echo ""
            echo "Pipeline Information:"
            echo "  Pipeline Name: $(Build.DefinitionName)"
            echo "  Pipeline ID: $(System.DefinitionId)"
            echo "  Build Number: $(Build.BuildNumber)"
            echo "  Build ID: $(Build.BuildId)"
            echo "  Build Reason: $(Build.Reason)"
            echo ""
            echo "Agent Pool Information:"
            echo "  Pool Name: $(ecp_ado_agent_pool_azure)"
            echo "  Agent Name: $(Agent.Name)"
            echo "  Agent Machine Name: $(Agent.MachineName)"
            echo "  Agent OS: $(Agent.OS)"
            echo "  Agent Architecture: $(Agent.OSArchitecture)"
            echo ""
            echo "Repository Information:"
            echo "  Repository: $(Build.Repository.Name)"
            echo "  Branch: $(Build.SourceBranchName)"
            echo ""
            echo "======================================"
            echo "      much more to follow here"
            echo "      ........................"
            echo "        ...................."
            echo "          ................"
            echo "======================================"

      - task: Bash@3
        name: azureImsQuery
        displayName: 'Azure Instance Metadata Service Query'
        inputs:
          targetType: inline
          script: |
            set -e
            echo "======================================"
            echo "  Azure Instance Metadata Service Info"
            echo "======================================"
            echo ""
            # Check if IMDS is accessible
            if ! curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2025-04-07" > /dev/null 2>&1; then
              echo "INFO: Instance Metadata Service not accessible (agent may not be running on Azure VM)"
              exit 0
            fi
            
            # Extract and set useful variables
            echo "=== Key Information ==="

            SUBSCRIPTION_ID=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/subscriptionId?api-version=2025-04-07&format=text")
            echo "Subscription ID: $SUBSCRIPTION_ID"

            VM_ID=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2025-04-07&format=text")
            echo "VM ID: $VM_ID"
            
            VM_RESOURCE_ID=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/resourceId?api-version=2025-04-07&format=text")
            echo "VM Resource ID: $VM_RESOURCE_ID"
            
            LOCATION=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2025-04-07&format=text")
            echo "Location: $LOCATION"
            
            RESOURCE_GROUP=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/resourceGroupName?api-version=2025-04-07&format=text")
            echo "Resource Group: $RESOURCE_GROUP"

            VM_SIZE=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2025-04-07&format=text")
            echo "VM Size: $VM_SIZE"

            VM_OS_TYPE=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/osType?api-version=2025-04-07&format=text")
            echo "VM OS Type: $VM_OS_TYPE"

            VM_IP_ADDRESS_PRIVATE=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/privateIpAddress?api-version=2025-04-07&format=text")
            echo "VM Private IP Address: $VM_IP_ADDRESS_PRIVATE"

            VM_IP_ADDRESS_SUBNET_ADDRESS=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/subnet/0/address?api-version=2025-04-07&format=text")
            VM_IP_ADDRESS_SUBNET_PREFIX=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/subnet/0/prefix?api-version=2025-04-07&format=text")
            VM_IP_ADDRESS_SUBNET_CIDR="${VM_IP_ADDRESS_SUBNET_ADDRESS}/${VM_IP_ADDRESS_SUBNET_PREFIX}"
            echo "VM Subnet: $VM_IP_ADDRESS_SUBNET_CIDR"            
            echo ""
            echo "=================================================="
