name: "$(BuildDefinitionName) - $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)"

# Exclude all triggers by default
trigger:
  branches:
    exclude:
      - '*'  # Exclude all branches
  paths:
    exclude:
      - '*'  # Exclude all paths

parameters:
  - name: ecp_environment_name
    type: string
    # default must be '<ecp_environment_name>' <-- will be replaced by pipeline deployment
    default: '<ecp_environment_name>'
  - name: terraform_version
    type: string
    default: latest
  - name: terragrunt_version
    type: string
    default: latest

variables:
- group: "ecp_bootstrap_${{ parameters.ecp_environment_name }}"

pool:
  name: $[variables.ecp_ado_agent_pool_azure]
  demands:
  - ImageOverride -equals ubuntu-24.04

stages:
  - stage: default
    displayName: 'Default'
    jobs:
    - job: adoPoolAnalysis
      displayName: 'ADO Pool Analysis'
      steps:
      - task: Bash@3
        name: adoPoolAnalysisScript
        displayName: 'Azure DevOps Pool Analysis'
        inputs:
          targetType: inline
          script: |
            echo "======================================"
            echo "       Azure DevOps Pool Analysis"
            echo "======================================"
            echo ""
            echo "Organization Information:"
            echo "  Organization URL: $(System.TeamFoundationCollectionUri)"
            echo "  Organization ID: $(System.CollectionId)"
            echo ""
            echo "Project Information:"
            echo "  Project Name: $(System.TeamProject)"
            echo "  Project ID: $(System.TeamProjectId)"
            echo ""
            echo "Pipeline Information:"
            echo "  Pipeline Name: $(Build.DefinitionName)"
            echo "  Pipeline ID: $(System.DefinitionId)"
            echo "  Build Number: $(Build.BuildNumber)"
            echo "  Build ID: $(Build.BuildId)"
            echo "  Build Reason: $(Build.Reason)"
            echo ""
            echo "Agent Pool Information:"
            echo "  Pool Name: $(ecp_ado_agent_pool_azure)"
            echo "  Agent Name: $(Agent.Name)"
            echo "  Agent Machine Name: $(Agent.MachineName)"
            echo "  Agent OS: $(Agent.OS)"
            echo "  Agent Architecture: $(Agent.OSArchitecture)"
            echo ""
            echo "Repository Information:"
            echo "  Repository: $(Build.Repository.Name)"
            echo "  Branch: $(Build.SourceBranchName)"
            echo ""
            echo "======================================"
            echo "      much more to follow here"
            echo "      ........................"
            echo "        ...................."
            echo "          ................"
            echo "======================================"
