parameters:
  - name: azureSubscription
    type: string
  - name: workingDir
    type: string
  - name: name
    type: string
  - name: displayName
    type: string
  - name: tfDestroy
    type: boolean
    default: false
    
jobs:
  - job: terragrunt_plan
    displayName: "Terragrunt Plan: ${{ parameters.displayName }}"
    container: terragrunt
    timeoutInMinutes: 120
    steps:
      - checkout: self

      - task: AzureCLI@2
        displayName: Generate json plan(s)
        name: generate_plans
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          addSpnToEnvironment: true
          visibleAzLogin: false
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "======= terragrunt version ======="
            echo "$(terragrunt --version)"
            echo "======= terraform version ======="
            echo "$(terragrunt run --working-dir "${{ parameters.workingDir }}" -- version)"
            echo "========================= ======="
            echo ""

            export ARM_TENANT_ID="$tenantId"
            export ARM_CLIENT_ID="$servicePrincipalId"
            export ARM_OIDC_TOKEN="$idToken"
            export ARM_CLIENT_SECRET="$servicePrincipalKey"
            if [ -n "$idToken" ] && [ -z "$servicePrincipalKey" ]; then export ARM_USE_OIDC="true"; else export ARM_USE_OIDC="false"; fi
            
            # use -detailed-exitcode which informs if there are changes in the plan

            if [ "${{ parameters.tfDestroy }}" = "True" ]; then
              echo "====== terraform DESTROY planning ======="
              terragrunt run --all --working-dir "${{ parameters.workingDir }}" --queue-exclude-external --non-interactive --provider-cache -- plan -destroy -parallelism=30 -detailed-exitcode
            else
              echo "====== terraform planning ======="
              terragrunt run --all --working-dir "${{ parameters.workingDir }}" --queue-exclude-external --non-interactive --provider-cache -- plan -parallelism=30 -detailed-exitcode
            fi

            rc=$?
            set -e
            if [[ $rc -eq 0 ]]; then
              echo "No changes, infrastructure is up-to-date."
              echo "##vso[task.setvariable variable=tf_plan_result;isOutput=true]unchanged"
            elif [[ $rc -eq 1 ]]; then
              echo "Terraform plan failed."
              exit 1
            elif [[ $rc -eq 2 ]]; then
              echo "Infrastructure changes detected."
              echo "##vso[task.setvariable variable=tf_plan_result;isOutput=true]changed"
            else
              echo "Unexpected exit code: $rc"
              exit $rc
            fi

            rm -rf "$(Build.ArtifactStagingDirectory)/plans"
            mkdir "$(Build.ArtifactStagingDirectory)/plans"
            plans=($(find . -iname *.tfplan))
            for plan in "${plans[@]}"; do
              dir=$(dirname $plan)
              dir=$(echo "$dir" | sed 's/\(.*\)\/\.terragrunt-cache\/.*/\1/')
              terragrunt show -json $(basename $plan) --working-dir=$dir > "$(Build.ArtifactStagingDirectory)/plans/$(basename $plan .tfplan).json"
            done
            echo "##vso[task.setvariable variable=planFailed]false"

      - script: |
          echo "##vso[task.setvariable variable=planFailed]true"
        name: report_plan_failed
        displayName: Set flag if run --all plan failed
        condition: failed()

      - task: PublishPipelineArtifact@1
        displayName: Publish plan(s) and analysis file(s)
        condition: succeeded()
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/plans"
          artifact: "tfplans_${{ parameters.name }}_$(System.JobAttempt)"
          publishLocation: "pipeline"

  - job: manual_validation_if_changes
    displayName: Wait for approval if resources are impacted
    timeoutInMinutes: 4320 # 3 days
    condition: and
      (
        eq(dependencies.terragrunt_plan.outputs['generate_plans.tf_plan_result'], 'changed'),
        in(dependencies.terragrunt_plan.result, 'Succeeded')
      )
    dependsOn:
      - terragrunt_plan
    pool: server
    steps:
      - task: ManualValidation@0
        displayName: Manual validation
        timeoutInMinutes: 4319 # 3 days - 1 minute (must be less than the job timeout)
        inputs:          
          notifyUsers: "$(approversTeamName)"
          instructions: "One or more of these plans have critical changes, please review them and accept or reject accordingly."
          onTimeout: "reject"

  - job: terragrunt_apply
    displayName: "Terragrunt apply: ${{ parameters.displayName }}"
    timeoutInMinutes: 120
    dependsOn:
      - terragrunt_plan
      - manual_validation_if_changes
    condition: and
      (
      in(dependencies.terragrunt_plan.result, 'Succeeded'),
      eq(dependencies.terragrunt_plan.outputs['generate_plans.tf_plan_result'], 'changed'),
      in(dependencies.manual_validation_if_changes.result, 'Succeeded', 'SucceededWithIssues')
      )
    container: terragrunt
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Execute apply
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          addSpnToEnvironment: true
          visibleAzLogin: false
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            export ARM_TENANT_ID="$tenantId"
            export ARM_CLIENT_ID="$servicePrincipalId"
            export ARM_OIDC_TOKEN="$idToken"
            export ARM_CLIENT_SECRET="$servicePrincipalKey"
            if [ -n "$idToken" ] && [ -z "$servicePrincipalKey" ]; then export ARM_USE_OIDC="true"; else export ARM_USE_OIDC="false"; fi

            if [ "${{ parameters.tfDestroy }}" = "True" ]; then
              echo "====== terraform destroy ======="
              terragrunt run --all --working-dir "${{ parameters.workingDir }}" --queue-exclude-external --non-interactive --provider-cache -- apply -destroy -parallelism=30
            else
              echo "====== terraform apply ======="
              terragrunt run --all --working-dir "${{ parameters.workingDir }}" --queue-exclude-external --non-interactive --provider-cache -- apply -parallelism=30
            fi
